mkdir bin/tournaments
cd ZED
g++  -c   -O3 -s         -DLINUX -DNO_OPENGLES    -std=c++17 -fpermissive                 -Wno-attributes -Wno-format -Wno-conversion-null -Wno-format-extra-args -Wno-unused-result -Wno-deprecated-declarations -Wno-trigraphs   -I"src" -I"external"   `pkg-config --cflags gtk+-3.0`    external/SDL_rotozoom/SDL_rotozoom.cpp   src/core.cpp  src/csv.cpp src/http_client.cpp  src/log.cpp  src/blob.cpp src/sha512.cpp src/crc32.cpp   src/renderer_sdl2.cpp  src/renderer.cpp   src/renderer_opengl.cpp src/opengl_extensions.cpp  src/renderer_opengles1_1.cpp   src/file.cpp  src/image.cpp  src/png.cpp  src/server.cpp  src/server_tcp.cpp  src/server_udp.cpp  src/socket.cpp  src/socket_tcp.cpp src/socket_udp.cpp  src/timer.cpp
ar rcs libZED.a *.o; rm *.o
g++  -c    -g   -D_DEBUG -DLINUX -DNO_OPENGLES    -std=c++17 -fpermissive                 -Wno-attributes -Wno-format -Wno-conversion-null -Wno-format-extra-args -Wno-unused-result -Wno-deprecated-declarations -Wno-trigraphs   -I"src" -I"external"   `pkg-config --cflags gtk+-3.0`    external/SDL_rotozoom/SDL_rotozoom.cpp   src/core.cpp  src/csv.cpp src/http_client.cpp  src/log.cpp  src/blob.cpp src/sha512.cpp src/crc32.cpp   src/renderer_sdl2.cpp  src/renderer.cpp   src/renderer_opengl.cpp src/opengl_extensions.cpp  src/renderer_opengles1_1.cpp   src/file.cpp  src/image.cpp  src/png.cpp  src/server.cpp  src/server_tcp.cpp  src/server_udp.cpp  src/socket.cpp  src/socket_tcp.cpp src/socket_udp.cpp  src/timer.cpp
ar rcs libZEDd.a *.o; rm *.o
cd ..


g++  -c -fpermissive  -O3  -s -std=c++17 -DLINUX                                          -Wno-attributes -Wno-format -Wno-conversion-null -Wno-format-extra-args -Wno-unused-result -Wno-deprecated-declarations -Wno-trigraphs       -I"."  -I"src"    -I"external"  `pkg-config --cflags gtk+-3.0`  "src/app.cpp"  "src/app_ajax.cpp"   "src/account.cpp"  "src/club.cpp"  "src/database.cpp"   "src/judoka.cpp"   "src/club.cpp"  "src/mat.cpp"   "src/remote_mat.cpp"   "src/match.cpp"  "src/matchtable.cpp"  "src/matchlog.cpp"  "src/timer.cpp"   "src/tournament.cpp"   "src/remote_tournament.cpp"   "src/weightclass.cpp"   "src/rule_set.cpp" "src/standing_data.cpp" "src/id.cpp" "src/error.cpp"    "src/localizer.cpp"  "src/window_linux.cpp"     "src/HttpServer/HttpServer.cpp" "external/mongoose/mongoose.cpp"     -ldl  -lpthread    `pkg-config --libs gtk+-3.0`     -ldl  -lpthread -lSDL2 -lSDL2_ttf -lfreetype  -lGL  -lEGL -lpng   -no-pie
ar rcs libjudoboard.a *.o; rm *.o

g++    -fpermissive  -O3  -s  -std=c++17 -DLINUX             -o "bin/judoboard"           -Wno-attributes -Wno-format -Wno-conversion-null -Wno-format-extra-args -Wno-unused-result -Wno-deprecated-declarations -Wno-trigraphs       -I"."   -I"src"   -I"external"  `pkg-config --cflags gtk+-3.0`  "src/main.cpp"                                                                                                                                                                             "libjudoboard.a"   -ldl  -lpthread   "ZED/libZED.a"  `pkg-config --libs gtk+-3.0`   -lSDL2 -lSDL2_ttf   -lfreetype  -lGL  -lEGL -lpng   -no-pie

g++  -c -fpermissive  -g      -std=c++17  -D_DEBUG  -DLINUX                               -Wno-attributes -Wno-format -Wno-conversion-null -Wno-format-extra-args -Wno-unused-result -Wno-deprecated-declarations -Wno-trigraphs       -I"."   -I"src"   -I"external"  `pkg-config --cflags gtk+-3.0`  "src/app.cpp"  "src/app_ajax.cpp"   "src/account.cpp"  "src/club.cpp"  "src/database.cpp"   "src/judoka.cpp"   "src/club.cpp"   "src/mat.cpp"   "src/remote_mat.cpp"   "src/match.cpp"  "src/matchtable.cpp"  "src/matchlog.cpp"  "src/timer.cpp"   "src/tournament.cpp"  "src/remote_tournament.cpp"   "src/weightclass.cpp"   "src/rule_set.cpp" "src/standing_data.cpp" "src/id.cpp" "src/error.cpp"    "src/localizer.cpp"  "src/window_linux.cpp"     "src/HttpServer/HttpServer.cpp" "external/mongoose/mongoose.cpp"      -ldl  -lpthread    `pkg-config --libs gtk+-3.0`     -ldl  -lpthread -lSDL2 -lSDL2_ttf -lfreetype  -lGL  -lEGL -lpng   -no-pie
ar rcs libjudoboardd.a *.o; rm *.o

g++    -fpermissive -g        -std=c++17 -D_DEBUG  -DLINUX   -o "bin/judoboard_Debug"     -Wno-attributes -Wno-format -Wno-conversion-null -Wno-format-extra-args -Wno-unused-result -Wno-deprecated-declarations -Wno-trigraphs       -I"."   -I"src"   -I"external"  `pkg-config --cflags gtk+-3.0`  "src/main.cpp"                                                                                                                                                                             "libjudoboardd.a"   "ZED/libZEDd.a"  `pkg-config --libs gtk+-3.0`     -ldl  -lpthread -lSDL2 -lSDL2_ttf   -lfreetype  -lGL  -lEGL -lpng   -no-pie

g++    -fpermissive  -O3  -s  -std=c++17 -DLINUX           -o "bin/judoboard_GTest"       -Wno-attributes -Wno-format -Wno-conversion-null -Wno-format-extra-args -Wno-unused-result -Wno-deprecated-declarations -Wno-trigraphs       -I"."   -I"src"   -I"external"  `pkg-config --cflags gtk+-3.0`   tests/account.cpp  tests/app.cpp  "tests/ajax.cpp"   tests/database.cpp  tests/judoka.cpp  tests/club.cpp  tests/id.cpp  tests/mat.cpp  tests/remote_mat.cpp   tests/match.cpp  tests/timer.cpp  tests/tournament.cpp                                           "libjudoboard.a"    -ldl  -lpthread   "ZED/libZED.a"   `pkg-config --libs gtk+-3.0`   -lSDL2 -lSDL2_ttf   -lfreetype  -lGL  -lEGL -lpng      -lgtest   -lgtest_main
g++    -fpermissive -g        -std=c++17 -D_DEBUG -DLINUX  -o "bin/judoboard_GTest_Debug" -Wno-attributes -Wno-format                                                                                                                  -I"."   -I"src"   -I"external"  `pkg-config --cflags gtk+-3.0`   tests/account.cpp  tests/app.cpp  "tests/ajax.cpp"   tests/database.cpp  tests/judoka.cpp  tests/club.cpp  tests/id.cpp  tests/mat.cpp  tests/remote_mat.cpp   tests/match.cpp  tests/timer.cpp  tests/tournament.cpp                                           "libjudoboardd.a"   -ldl  -lpthread   "ZED/libZEDd.a"  `pkg-config --libs gtk+-3.0`   -lSDL2 -lSDL2_ttf   -lfreetype  -lGL  -lEGL -lpng      -lgtest   -lgtest_main