#include <algorithm>
#include <random>
#include "single_elimination.h"
#include "weightclass.h"
#include "tournament.h"
#include "localizer.h"
#include "match.h"



using namespace Judoboard;



SingleElimination::SingleElimination(IFilter* Filter, const ITournament* Tournament)
	: MatchTable(Filter, Tournament)
{
	if (Filter)
		SetTournament(Filter->GetTournament());
	GenerateSchedule();
}



SingleElimination::SingleElimination(Weight MinWeight, Weight MaxWeight, const ITournament* Tournament)
	: MatchTable(new Weightclass(MinWeight, MaxWeight, Tournament), Tournament)
{
}



SingleElimination::SingleElimination(const YAML::Node& Yaml, const ITournament* Tournament)
	: MatchTable(Yaml, Tournament)
{
	if (Yaml["third_place_match"])
		m_ThirdPlaceMatch = Yaml["third_place_match"].as<bool>();
	if (Yaml["fifth_place_match"])
		m_FifthPlaceMatch = Yaml["fifth_place_match"].as<bool>();
}



SingleElimination::SingleElimination(const MD5::Weightclass& Weightclass_, const ITournament* Tournament)
	: MatchTable(new Weightclass(Weightclass_, Tournament), Tournament)
{
}



void SingleElimination::operator >> (YAML::Emitter& Yaml) const
{
	MatchTable::operator >>(Yaml);

	if (m_ThirdPlaceMatch)
		Yaml << YAML::Key << "third_place_match" << YAML::Value << m_ThirdPlaceMatch;
	if (m_FifthPlaceMatch)
		Yaml << YAML::Key << "fifth_place_match" << YAML::Value << m_FifthPlaceMatch;
}



void SingleElimination::ToString(YAML::Emitter& Yaml) const
{
	MatchTable::ToString(Yaml);

	Yaml << YAML::Key << "third_place" << YAML::Value << IsThirdPlaceMatch();
	Yaml << YAML::Key << "fifth_place" << YAML::Value << IsFifthPlaceMatch();
}



std::string SingleElimination::GetHTMLForm()
{
	std::string ret = R"(
<div>
	<label style="width:150px;float:left;margin-top:5px;" id="label_mf3">Match for 3rd place</label>
		<input type="checkbox" id="mf3" class="switch-input">
		<label style="padding-top:0px;padding-bottom:0px;margin-top:5px;margin-bottom:20px;" class="switch-label" for="mf3">
		<span class="toggle-on" id="mf3_enabled"></span><span class="toggle-off" id="mf3_disabled"></span>
	</label>
</div>

<div>
	<label style="width:150px;float:left;margin-top:5px;" id="label_mf5">Match for 5th place</label>
		<input type="checkbox" id="mf5" class="switch-input">
		<label style="padding-top:0px;padding-bottom:0px;margin-top:5px;margin-bottom:20px;" class="switch-label" for="mf5">
		<span class="toggle-on" id="mf5_enabled"></span><span class="toggle-off" id="mf5_disabled"></span>
	</label>
</div>
)";

	ret += MatchTable::GetHTMLForm();

	return ret;
}



void SingleElimination::GenerateSchedule()
{
	if (GetStatus() != Status::Scheduled)
		return;

	for (auto it = m_Schedule.begin(); it != m_Schedule.end();)
	{
		if ((*it)->IsAutoGenerated())
			it = m_Schedule.erase(it);
		else
			++it;
	}

	if (GetParticipants().size() <= 3)
		m_RecommendedNumMatches_Before_Break = 1;
	else
		m_RecommendedNumMatches_Before_Break = 2;

	if (GetParticipants().size() <= 1)
		return;

	const auto rounds = GetNumberOfRounds();
	const auto max_start_pos = GetMaxStartPositions();
	
	//Round 1
	std::vector<Match*> lastRound;
	std::vector<Match*> nextRound;

	auto create_pair = [&](int i) {
		auto new_match = CreateAutoMatch(GetJudokaByStartPosition(i-1),
										 GetJudokaByStartPosition(i-1 + max_start_pos/2));
		nextRound.emplace_back(new_match);
	};

	if (rounds == 2)//4 participants hardcoded
	{
		for (int j = 0; j < 2; j++)
			create_pair(1 + j);
	}

	else if (rounds == 3)//8 participants hardcoded
	{
		for (int j = 0; j < 2; j++)
		{
			create_pair(1 + j);
			create_pair(3 + j);
		}
	}

	else if (rounds == 4)//16 participants hardcoded
	{
		for (int j = 0; j < 2; j++)
		{
			create_pair(1 + j);
			create_pair(5 + j);
			create_pair(3 + j);
			create_pair(7 + j);
		}
	}

	else if (rounds == 5)//32 participants hardcoded
	{
		for (int j = 0; j < 2; j++)
		{
			create_pair(1  + j);
			create_pair(9  + j);
			create_pair(5  + j);
			create_pair(13 + j);
			create_pair(3  + j);
			create_pair(11 + j);
			create_pair(7  + j);
			create_pair(15 + j);
		}
	}

	else if (rounds == 6)//64 participants hardcoded
	{
		for (int j = 0; j < 2; j++)
		{
			create_pair(1  + j);
			create_pair(17 + j);
			create_pair(9  + j);
			create_pair(25 + j);
			create_pair(5  + j);
			create_pair(21 + j);
			create_pair(13 + j);
			create_pair(29 + j);
			create_pair(3  + j);
			create_pair(19 + j);
			create_pair(11 + j);
			create_pair(27 + j);
			create_pair(7  + j);
			create_pair(23 + j);
			create_pair(15 + j);
			create_pair(31 + j);
		}
	}

	else
	{
		for (size_t i = 0; i < max_start_pos/2; ++i)
		{
			auto new_match = CreateAutoMatch(GetJudokaByStartPosition(i),
											 GetJudokaByStartPosition(i + max_start_pos/2));
			nextRound.emplace_back(new_match);
		}
	}

	//Additional rounds
	for (int round = 1; round < rounds; ++round)
	{
		lastRound = std::move(nextRound);

		for (size_t i = 0; i < lastRound.size(); i += 2)
		{
			if (i+1 >= lastRound.size())
				break;

			auto match1 = lastRound[i];
			auto match2 = lastRound[i+1];

			auto new_match = AddMatchForWinners(match1, match2);
			nextRound.emplace_back(new_match);
		}
	}


	//Add additional match for 3rd place
	if (IsThirdPlaceMatch() && m_Schedule.size() >= 3)
	{
		auto match1 = m_Schedule[m_Schedule.size() - 3];
		auto match2 = m_Schedule[m_Schedule.size() - 2];

		auto third_place = CreateAutoMatch(nullptr, nullptr);
		third_place->SetDependency(Fighter::White, DependencyType::TakeLoser, match1);
		third_place->SetDependency(Fighter::Blue,  DependencyType::TakeLoser, match2);

		//Swap matches so that match for 1st place is still the last one
		std::swap(m_Schedule[m_Schedule.size() - 1], m_Schedule[m_Schedule.size() - 2]);
	}
	

	//Add additional matches for 5th place
	if (IsFifthPlaceMatch() && m_Schedule.size() >= 8)
	{
		int offset = 3;//Final and two semi finals
		if (IsThirdPlaceMatch())
			offset = 4;

		auto match1 = m_Schedule[m_Schedule.size() - 1 - offset - 3];
		auto match2 = m_Schedule[m_Schedule.size() - 1 - offset - 2];
		auto match3 = m_Schedule[m_Schedule.size() - 1 - offset - 1];
		auto match4 = m_Schedule[m_Schedule.size() - 1 - offset];

		//Order gets fixed at the end
		auto semi2 = CreateAutoMatch(nullptr, nullptr);
		auto fifth = CreateAutoMatch(nullptr, nullptr);
		auto semi1 = CreateAutoMatch(nullptr, nullptr);

		semi1->SetDependency(Fighter::White, DependencyType::TakeLoser, match1);
		semi1->SetDependency(Fighter::Blue,  DependencyType::TakeLoser, match2);

		semi2->SetDependency(Fighter::White, DependencyType::TakeLoser, match3);
		semi2->SetDependency(Fighter::Blue,  DependencyType::TakeLoser, match4);

		fifth->SetDependency(Fighter::White, DependencyType::TakeWinner, semi1);
		fifth->SetDependency(Fighter::Blue,  DependencyType::TakeWinner, semi2);

		//Swap matches so that match for 1st place is still the last one
		offset = 3;

		std::swap(m_Schedule[m_Schedule.size() - 1 - offset - 2], m_Schedule[m_Schedule.size() - 1 - 2]);
		std::swap(m_Schedule[m_Schedule.size() - 1 - offset - 1], m_Schedule[m_Schedule.size() - 1 - 1]);
		std::swap(m_Schedule[m_Schedule.size() - 1 - offset],     m_Schedule[m_Schedule.size() - 1]);

		if (IsThirdPlaceMatch())
			std::swap(m_Schedule[m_Schedule.size() - 1 - offset - 3], m_Schedule[m_Schedule.size() - 1 - 3]);
	}


	//Add additional matches for best of three
	if (IsBestOfThree())
		AddMatchesForBestOfThree();
}



MatchTable::Results SingleElimination::CalculateResults() const
{
	Results ret;

	if (GetParticipants().size() == 0)
		return ret;

	if (GetParticipants().size() == 1)
	{
		ret.Add(GetParticipants()[0], this);
		return ret;
	}

	if (m_Schedule.size() == 0)
		return ret;

	//Get final match
	const Match* lastMatch = m_Schedule[m_Schedule.size() - 1];

	if (lastMatch->HasConcluded())
	{
		ret.Add(lastMatch->GetWinner(), this);
		ret.Add(lastMatch->GetLoser(),  this);
	}
	else
		return ret;

	if (IsThirdPlaceMatch())
	{
		const Match* third_place_match = m_Schedule[m_Schedule.size() - 2];
		ret.Add(third_place_match->GetWinner(), this);
		ret.Add(third_place_match->GetLoser(),  this);
	}

	if (IsThirdPlaceMatch() && IsFifthPlaceMatch())
	{
		//int offset = 4;
		//if (IsThirdPlaceMatch())
		//offset = 5;

		int offset = 5;

		const Match* fifth_place_match = m_Schedule[m_Schedule.size() - offset];
		ret.Add(fifth_place_match->GetWinner(), this);
		ret.Add(fifth_place_match->GetLoser(),  this);
	}

	return ret;
}



const std::string SingleElimination::ToHTML() const
{
	std::string ret;

	ret += "<a href=\"#matchtable_add.html?id=" + (std::string)GetUUID() + "\">" + GetDescription() + "</a>";

	ret += " / " + Localizer::Translate("Mat") + " " + std::to_string(GetMatID()) + " / " + GetRuleSet().GetName() + "<br/>";

	ret += "<table border='1' rules='all'>";

	const auto rounds = GetNumberOfRounds();
	const auto N = pow(2, rounds);


	auto renderMatchIndex = [this, N](size_t matchIndex, std::string style = "") -> std::string {

		if (matchIndex >= GetSchedule().size())
			return "";

		auto match = GetSchedule()[matchIndex];

		std::string ret = "<td style=\"" + style + "\">";

		if (!match->IsEmptyMatch())
			ret += "<a href='#edit_match.html?id=" + (std::string)match->GetUUID() + "'>";

		//Output name of fighters
		if (match->GetFighter(Fighter::White))
			ret += match->GetFighter(Fighter::White)->GetName(NameStyle::GivenName);
		else if (match->HasDependentMatches())
			ret += "???";
		else
			ret += "- - -";

		ret += " vs. ";

		if (match->GetFighter(Fighter::Blue))
			ret += match->GetFighter(Fighter::Blue)->GetName(NameStyle::GivenName);
		else if (match->HasDependentMatches())
			ret += "???";
		else
			ret += "- - -";

		//Output result
		if (match->IsRunning())
			ret += "<br/>" + Localizer::Translate("In Progress");
		else if (match->HasConcluded() && !match->IsCompletelyEmptyMatch())
		{
			const auto& result = match->GetResult();
			if (result.m_Winner == Winner::White)
				ret += "<br/>"   + std::to_string((int)result.m_Score) + ":0";
			else
				ret += "<br/>0:" + std::to_string((int)result.m_Score);

			ret += " (" + Timer::TimestampToString(result.m_Time) + ")";
		}

		if (!match->IsEmptyMatch())
			ret += "</a>";
		ret += "</a></td>";

		return ret;
	};


	auto renderMatch = [this, N, renderMatchIndex](size_t roundIndex, int matchOfRound) -> std::string {
		int matchIndex = 0;
		for (int i = 1; i <= roundIndex; ++i)
			matchIndex += (int)(N / pow(2.0, i));

		matchIndex += matchOfRound;

		if (IsThirdPlaceMatch() && matchIndex >= GetSchedule().size() - 2)
			matchIndex++;
		if (IsFifthPlaceMatch() && matchIndex >= GetSchedule().size() - 5)
			matchIndex += 3;

		if (IsBestOfThree())
			matchIndex = matchIndex * 3;

		std::string style;

		if (roundIndex == 0)
			style = "border-left-style: hidden;";
		if (matchOfRound % 2 == 0)
			style += "border-right-style: hidden;";

		return renderMatchIndex(matchIndex, style);
	};

	size_t width = 100;
	if (rounds > 0)
		width = 100 / rounds;

	ret += "<tr style='height: 5mm; text-align: center'>";
	for (int round = 0; round < rounds; ++round)
		ret += "<th width=\"" + std::to_string(width) + "%\">" + Localizer::Translate("Round") + " " + std::to_string(round + 1) + "</th>";
	ret += "</tr>";

	for (int y = 0; y < N; ++y)
	{
		ret += "<tr style='height: 5mm; text-align: center'>";

		for (size_t round = 0; round < rounds; ++round)
		{
			if ( (y + (int)std::pow(2, round) + 1) % (int)std::pow(2, round+1) != 0)
			{
				std::string style;
				if (round == 0 || (y + (int)std::pow(2, round) + (int)std::pow(2, round-1) ) % (int)std::pow(2, round+1)  >= (int)std::pow(2, round))
					style += "border-left-style: hidden;";
				if (round+1 == rounds)
					style += "border-right-style: hidden;";

				ret += "<td style=\"" + style + "border-bottom-style: hidden; \"></td>";
				continue;
			}

			const int matchOfRound = y / (int)std::pow(2, round+1);
			ret += renderMatch(round, matchOfRound);
		}

		ret += "</tr>";
	}

	ret += "</table>";


	if (IsThirdPlaceMatch())
	{
		ret += "<table width=\"" + std::to_string(width) + "%\" border='1' rules='all' style=\"margin-bottom: 5mm;\">";

		ret += "<tr style='height: 5mm; text-align: center'>";
		ret += "<th>" + Localizer::Translate("3rd Place Match") + "</th>";
		ret += "</tr>";

		ret += "<tr style='height: 5mm; text-align: center'>";
		ret += renderMatchIndex(m_Schedule.size() - 2);
		ret += "</tr>";

		ret += "</table>";
	}


	if (IsFifthPlaceMatch())
	{
		ret += "<table border='1' rules='all' style=\"margin-bottom: 5mm;\">";

		ret += "<tr style='height: 5mm; text-align: center'>";
		ret += "<th colspan=\"2\" width=\"" + std::to_string(width*2) + "%\">" + Localizer::Translate("5th Place Match") + "</th>";
		ret += "</tr>";

		int offset = 4;
		if (IsThirdPlaceMatch())
			offset = 5;

		ret += "<tr style='height: 5mm; text-align: center'>";
		ret += renderMatchIndex(m_Schedule.size() - offset - 2, "border-left-style: hidden; border-right-style: hidden;");
		ret += "<td style=\"border-bottom-style: hidden; border-right-style: hidden;\"></td>";
		ret += "</tr>";

		ret += "<tr style='height: 5mm; text-align: center'>";
		ret += "<td style=\"border-bottom-style: hidden; border-left-style: hidden;\"></td>";
		ret += renderMatchIndex(m_Schedule.size() - offset, "border-right-style: hidden;");
		ret += "</tr>";

		ret += "<tr style='height: 5mm; text-align: center'>";
		ret += renderMatchIndex(m_Schedule.size() - offset - 1, "border-left-style: hidden;");
		ret += "<td style=\"border-bottom-style: hidden; border-right-style: hidden;\"></td>";
		ret += "</tr>";

		ret += "</table>";
	}

	ret += ResultsToHTML();	

	return ret;
}