name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build1:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod u+x *.sh && ./dependencies.sh
    - name: make
      run: ./compile.sh
      
  build2:
    name: Build on Raspberry Pi 4
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod u+x *.sh
    - name: make
      run: ./compile.sh
    
  build3:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: change directory
      run: dir; cd vsprojects; dir
    - name: nuget1
      run: dir; cd vsprojects; dir; nuget install ZED\packages.config        -OutputDirectory packages
    - name: nuget2
      run: dir; cd vsprojects; dir; nuget install GoogleTest\packages.config -OutputDirectory packages
    - name: msbuild
      run: dir; cd vsprojects; dir; msbuild Judoboard.sln
