name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod u+x *.sh && ./dependencies.sh
    - name: make
      run: ./compile.sh
    - name: run tests
      run: ./run_tests.sh
