name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_run:
    workflows: ["Unit Tests"]
    branches: [master]
    types:
      - completed

jobs:
  release-job:
    name: Release
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: build
        run: dir; .\compile64.bat
      - name: package
        run: dir; .\package.bat
      - name: zip
        run: cd bin; 7z a package.zip *
      - name: version
        run: echo "::set-output name=version::$(./bin/Judoboard.exe --version)"
        id: version
      - name: Create Release
        uses: actions/create-release@latest
        id: create_release
        with:
          draft: false
          prerelease: true
          tag_name: Judoboard
          release_name: Judoboard ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Windows Artifact
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .\bin\package.zip
          asset_name: Judoboard.zip
          asset_content_type: application/zip
