name: Release

on:
  workflow_run:
    workflows:
      - Unit Tests
    types:
      - completed

jobs:
  release-job:
    name: Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: echo "The workflow works!!"
