name: Remote Mat

on:
  push:
    branches: [ remote-mat ]
  pull_request:
    branches: [ remote-mat ]

jobs:
  build1:
    name: Build and Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod u+x *.sh && ./dependencies.sh
    - name: make
      run: ./compile.sh
    - name: run tests
      run: ./run_tests.sh
      
  build2:
    name: Build and Test on Raspberry Pi 4
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod u+x *.sh
    - name: make
      run: ./compile.sh
    - name: run tests
      run: ./run_tests.sh
    - name: run tests debug
      run: ./run_tests_debug.sh