name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test1:
    name: Unit Tests on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod u+x *.sh && ./dependencies.sh && XDG_RUNTIME_DIR=. && sudo apt-get install gdb
    - name: make
      run: ./compile.sh
    - name: run tests
      run: ./run_tests.sh
    - name: debug tests
      run: cd bin && echo "r\nbt" > commands; gdb ./judoboard_GTest_Debug --command=commands && cd ..
      
  test2:
    name: Unit Tests on Raspberry Pi 4
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod u+x *.sh
    - name: make
      run: ./compile.sh
    - name: run tests
      run: ./run_tests.sh
    - name: debug tests
      run: cd bin && echo "r\nbt" > commands; gdb ./judoboard_GTest_Debug --command=commands && cd ..
