name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod u+x *.sh && ./dependencies.sh && XDG_RUNTIME_DIR=. && sudo apt-get install gdb
    - name: make
      run: ./compile.sh
    - name: run tests
      run: ./run_tests.sh
    - name: debug tests
      run: cd bin && gdb ./judoboard_GTest_Debug --eval-command=r && cd ..
