name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test1:
    name: Unit Tests on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod u+x *.sh && ./dependencies.sh && XDG_RUNTIME_DIR=. && sudo apt-get install gdb
    - name: make
      run: ./compile.sh
    - name: run tests
      run: ./run_tests.sh
    - name: debug tests
      run: cd bin && gdb ./judoboard_test_debug --eval-command=r bt && cd ..
      
  test2:
    name: Unit Tests on Raspberry Pi 4
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod u+x *.sh
    - name: make
      run: ./compile.sh
    - name: run tests
      run: ./run_tests.sh
    - name: debug tests
      run: cd bin && gdb ./judoboard_test_debug --eval-command=r bt && cd ..
      
  test3:
    name: Unit Tests on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: change directory
      run: dir; cd vsprojects; dir
    - name: nuget1
      run: dir; cd vsprojects; dir; nuget install ZED\packages.config        -OutputDirectory packages
    - name: nuget2
      run: dir; cd vsprojects; dir; nuget install GoogleTest\packages.config -OutputDirectory packages
    - name: compile
      run: dir; .\compile.bat
    - name: create folder
      run: dir; cd bin\Release; xcopy ..\assets assets\ /S /Y; xcopy ..\html   html\   /S /Y; mkdir tournaments
    - name: Run Tests
      run: dir; cd bin\Release; dir; .\GoogleTest.exe --gtest_filter=Mat*
